apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::699388635232:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-79G3879GMJJR
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::699388635232:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-07-15T10:20:13Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1652"
  uid: 83356713-a33e-493e-a8a6-c51833d51ae5
